version: 2
jobs:

    unit-test:
        machine: true
        steps:
            - checkout
            - run: echo "Running unit tests"

    integration-test:
        machine: true
        steps:
            - checkout
            - run: echo "Running integration tests"

    stress-test:
        machine: true
        steps:
            - checkout
            - run: echo "Running stress tests"
    build:
        machine: true
        steps:
            - checkout
            - run:
                name: Setup the commit sha
                command: | 
                    echo 'export TAG=$(echo $CIRCLE_SHA1 | cut -c 1-8)' >> $BASH_ENV
                    source $BASH_ENV
            - run:
                name: Build the Image
                command: docker build -t docker.io/ilyeshammadi/aliwhat:$CIRCLE_BRANCH-$TAG .
            - run:
                name: Login and push to the Registry
                command: |
                    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
                    docker push docker.io/ilyeshammadi/aliwhat:$CIRCLE_BRANCH-$TAG

    deploy-prod:
        machine: true
        steps:
            - run: echo "Deploy to production"

    deploy-staging:
        machine: true
        steps:
            - run: echo "Deploy to staging"

workflows:
  version: 2
  workflow:
    jobs:
        - unit-test
        - integration-test
        - stress-test:
            filters:
                branches:
                    only:
                        - master
        - build:
            requires:
                - unit-test
                - integration-test
                - stress-test
            filters:
                branches:
                    only:
                        - master
                        - develop
                tags:
                    only: /^\d+.\d+/

        
        # Hold before deploying to production
        # Production is only triggerd on releases
        - hold:
            type: approval
            requires:
                - build
            filters:
                tags:
                    only: /^\d+.\d+/
        - deploy-prod:
            requires:
                - hold
        
        # Deploy only when commits to develop branch
        - deploy-staging:
            requires:
                - build
            filters:
                branches:
                    only:
                        - develop