version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

     # build the application image
     - run: docker build -t docker.io/ilyeshammadi/aliwhat:$CIRCLE_BRANCH-$CIRCLE_SHA1 .

    # deploy the image
     - run: docker push docker.io/ilyeshammadi/aliwhat:$CIRCLE_BRANCH-$CIRCLE_SHA1